import cv2
import mediapipe as mp
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import time
import sys
import os

# Import local module 'pd' to reuse code and model architecture
# This must be in the same directory as pd.py
try:
    import pd as pd_module
except ImportError:
    print("Error: Could not import 'pd.py'. Make sure this script is in the 'Parkinson-Pipeline' directory.")
    sys.exit(1)

# --- CONFIGURATION ---
MODEL_PATH = "pd_detection_model.pth"
CLASSES = ['Healthy', 'Parkinson']
SEQ_LENGTH = 240 # Updated from 120
# Exact feature list from training (generated by PCA selection)
SELECTED_FEATURES = [
    'Brow micro-expression variance mean','Brow micro-expression rapid changes count','Brow velocity (mean)','Brow velocity (std)',
    'Right brow raise (mean)','Right brow raise (std)','Left brow raise (mean)','Left brow raise (std)',
    'Inner brow raise (mean)','Inner brow raise (std)','Brow asymmetry (mean)','Temporal brow asymmetry variance',
    'Brow frequency mean','Brow peak frequency','Brow tremor power','Brow tremor index',
    'Brow Left surface vector magnitude mean','Brow Left surface variance (current)','Brow Left surface variance mean',
    'Brow Left surface variance std','Brow Left surface variance min','Brow Left surface variance max',
    'Brow Left surface dominant angle mean','Brow Left surface dominant angle std','Brow Right surface vector magnitude mean',
    'Brow Right surface variance (current)','Brow Right surface variance mean','Brow Right surface variance std',
    'Brow Right surface variance min','Brow Right surface variance max','Brow Right surface dominant angle mean',
    'Brow Right surface dominant angle std','Cheek puff micro-expression variance mean','Cheek puff rapid changes count',
    'Cheek raise (mean)','Cheek raise (std)','Cheek velocity (mean)','Cheek velocity (std)','Cheek frequency mean',
    'Cheek asymmetry (mean)','Cheek tremor power','Cheek tremor index','Cheek Left surface vector magnitude mean',
    'Cheek Left surface variance (current)','Cheek Left surface variance mean','Cheek Left surface variance std',
    'Cheek Left surface variance min','Cheek Left surface variance max','Cheek Left surface dominant angle mean',
    'Cheek Left surface dominant angle std','Cheek Right surface vector magnitude mean','Cheek Right surface variance (current)',
    'Cheek Right surface variance mean','Cheek Right surface variance std','Cheek Right surface variance min',
    'Cheek Right surface variance max','Cheek Right surface dominant angle mean','Cheek Right surface dominant angle std',
    'Eye widening micro-expression variance mean','Eye widening rapid changes count','Eye ratio (mean)','Eye ratio (std)',
    'Blink rate','Eye squint velocity (mean)','Eye squint velocity (std)','Eye Left surface vector magnitude mean',
    'Eye Left surface variance (current)','Eye Left surface variance mean','Eye Left surface variance std',
    'Eye Left surface variance min','Eye Left surface variance max','Eye Left surface dominant angle mean',
    'Eye Left surface dominant angle std','Eye Right surface vector magnitude mean','Eye Right surface variance (current)',
    'Eye Right surface variance mean','Eye Right surface variance std','Eye Right surface variance min',
    'Eye Right surface variance max','Eye Right surface dominant angle mean','Eye Right surface dominant angle std',
    'Jaw opening (mean)','Jaw opening (std)','Jaw opening (min)','Jaw opening (max)','Jaw velocity (mean)',
    'Jaw velocity (std)','Jaw asymmetry (mean)','Jaw asymmetry (max)','Jaw rapid changes count','Jaw significant movements count',
    'Jaw frequency mean','Jaw peak frequency','Jaw Left surface vector magnitude mean','Jaw Left surface variance (current)',
    'Jaw Left surface variance mean','Jaw Left surface variance std','Jaw Left surface variance min','Jaw Left surface variance max',
    'Jaw Left surface dominant angle mean','Jaw Left surface dominant angle std','Jaw Right surface vector magnitude mean',
    'Jaw Right surface variance (current)','Jaw Right surface variance mean','Jaw Right surface variance std',
    'Jaw Right surface variance min','Jaw Right surface variance max','Jaw Right surface dominant angle mean',
    'Jaw Right surface dominant angle std','Lip micro-expression variance mean','Lip micro-expression rapid changes count',
    'Lip opening (mean)','Lip opening (std)','Lip opening (min)','Lip opening (max)','Lip velocity (mean)',
    'Lip velocity (std)','Lip significant movements count','Lip frequency mean','Lip peak frequency','Lip corner asymmetry (mean)',
    'Lip corner asymmetry (max)','Lip Left surface vector magnitude mean','Lip Left surface variance (current)',
    'Lip Left surface variance mean','Lip Left surface variance std','Lip Left surface variance min','Lip Left surface variance max',
    'Lip Left surface dominant angle mean','Lip Left surface dominant angle std','Lip Right surface vector magnitude mean',
    'Lip Right surface variance (current)','Lip Right surface variance mean','Lip Right surface variance std',
    'Lip Right surface variance min','Lip Right surface variance max','Lip Right surface dominant angle mean',
    'Lip Right surface dominant angle std','Mouth micro-expression variance mean','Mouth micro-expression rapid changes count',
    'Mouth opening (mean)','Mouth opening (std)','Mouth opening (min)','Mouth opening (max)','Mouth velocity (mean)',
    'Mouth velocity (std)','Mouth significant movements count','Mouth frequency mean','Mouth peak frequency',
    'Mouth corner asymmetry (mean)','Mouth corner asymmetry (max)','Mouth Left surface vector magnitude mean',
    'Mouth Left surface variance (current)','Mouth Left surface variance mean','Mouth Left surface variance std',
    'Mouth Left surface variance min','Mouth Left surface variance max','Mouth Left surface dominant angle mean',
    'Mouth Left surface dominant angle std','Mouth Right surface vector magnitude mean','Mouth Right surface variance (current)',
    'Mouth Right surface variance mean','Mouth Right surface variance std','Mouth Right surface variance min',
    'Mouth Right surface variance max','Mouth Right surface dominant angle mean','Mouth Right surface dominant angle std'
]

# --- SYSTEM CLASS ---
class ParkinsonDetectionSystem:
    def __init__(self, model_path):
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.feature_dim = len(SELECTED_FEATURES)
        self.hidden_dim = 64 # Updated to match new model
        self.num_classes = len(CLASSES)
        
        # Initialize Model using the class from pd_module to ensure compatibility
        try:
            # Note: OptimizedCNNLSTM might have 3 layers now, check pd.py default
            # pd.py: def __init__(self, input_dim, hidden_dim, num_classes, num_layers=3):
            self.model = pd_module.OptimizedCNNLSTM(self.feature_dim, self.hidden_dim, self.num_classes, num_layers=3)
            # Load state dict
            state_dict = torch.load(model_path, map_location=self.device)
            self.model.load_state_dict(state_dict)
            self.model.to(self.device)
            self.model.eval()
            print(f"Model loaded successfully from {model_path}")
        except Exception as e:
            print(f"Failed to load model: {e}")
            sys.exit(1)
            
        self.mp_face_mesh = mp.solutions.face_mesh
        self.mp_drawing = mp.solutions.drawing_utils

        # Region configs for visualization
        self.region_configs = [
            ('Brow', pd_module.left_brow_idx_surface, pd_module.right_brow_idx_surface, (0, 255, 0)),
            ('Cheek', pd_module.left_cheek_idx_surface, pd_module.right_cheek_idx_surface, (255, 0, 0)),
            ('Eye', pd_module.left_eye_idx_surface, pd_module.right_eye_idx_surface, (0, 0, 255)),
            ('Jaw', pd_module.left_jaw_idx_surface, pd_module.right_jaw_idx_surface, (255, 255, 0)),
            ('Lips', pd_module.left_lip_idx_surface, pd_module.right_lip_idx_surface, (255, 0, 255)),
            ('Mouth', pd_module.left_mouth_idx_surface, pd_module.right_mouth_idx_surface, (0, 255, 255)),
        ]

    def draw_surface_vectors(self, frame, landmarks, prev_landmarks, w, h):
        if prev_landmarks is None: return
        
        for name, l_idx, r_idx, color in self.region_configs:
            # Use the module's function to get vector stats
            # We need to pass raw landmarks here, similar to vTwo.py
            # But wait, pd.py compute_surface_vectors_split expects landmarks.
            # vTwo.py passes: compute_surface_vectors_split(landmarks, prev_landmarks, l_idx, r_idx)
            # where landmarks are [[x,y,z], ...]
            
            data = pd_module.compute_surface_vectors_split(landmarks, prev_landmarks, l_idx, r_idx)
            
            for side_key, side_data in [('left', data['left']), ('right', data['right'])]:
                positions = side_data['positions']
                mean_mag = side_data['mean_mag']
                angle = side_data['angle']

                if len(positions) == 0 or mean_mag < 0.0008:
                    continue

                # Compute average direction vector from angle
                avg_dir = np.array([np.cos(angle), np.sin(angle)])

                # Compute center position
                center_pos = np.mean(positions, axis=0) if positions else np.array([0, 0, 0])
                center_x = int(center_pos[0] * w)
                center_y = int(center_pos[1] * h)

                # Scale arrow length (heuristic from vTwo.py)
                base_scale = 20
                max_length = 40 # Increased visibility
                min_length = 5
                arrow_length = min(max(mean_mag * w * base_scale * 30, min_length), max_length)

                dx = avg_dir[0] * arrow_length
                dy = avg_dir[1] * arrow_length

                end_x = int(center_x + dx)
                end_y = int(center_y + dy)

                # Draw the arrow
                cv2.arrowedLine(frame, (center_x, center_y), (end_x, end_y), color, 2, tipLength=0.3)

                # Label
                # label = name[0] + ('L' if side_key == 'left' else 'R')
                # cv2.putText(frame, label, (center_x - 10, center_y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.4, color, 1)

    def process_video_file(self, video_path):
        if not os.path.exists(video_path):
            print(f"Error processing video: File not found {video_path}")
            return

        print(f"Processing video: {video_path}")
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            print("Error: Could not open video.")
            return

        # Reset buffers in the pd module to clear previous state
        pd_module.reset_buffers()
        pd_module._prev_landmarks_global = None 
        
        extracted_data = []
        frame_idx = 0
        
        with self.mp_face_mesh.FaceMesh(
            refine_landmarks=True, max_num_faces=1, 
            min_detection_confidence=0.5, min_tracking_confidence=0.5
        ) as face_mesh:
            
            while cap.isOpened():
                ret, frame = cap.read()
                if not ret:
                    break
                
                frame_idx += 1
                
                # Convert for MediaPipe
                image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                image_rgb.flags.writeable = False
                results = face_mesh.process(image_rgb)
                image_rgb.flags.writeable = True
                
                # Visualization frame
                vis_frame = frame.copy()
                h, w, _ = vis_frame.shape

                landmarks_list = None
                if results.multi_face_landmarks:
                    landmarks = results.multi_face_landmarks[0].landmark
                    landmarks_list = [[lm.x, lm.y, lm.z] for lm in landmarks]
                    
                    prev_lm = pd_module._prev_landmarks_global
                    
                    # Normalize
                    lm_list_norm = pd_module.normalize_for_rotation_distance(landmarks_list, prev_lm)
                    
                    # Extract Features
                    features_dict = {}
                    features_dict.update(pd_module.compute_brow_features(lm_list_norm, prev_lm))
                    features_dict.update(pd_module.compute_cheek_features(lm_list_norm, prev_lm))
                    features_dict.update(pd_module.compute_eye_features(lm_list_norm, prev_lm))
                    features_dict.update(pd_module.compute_jaw_features(lm_list_norm, prev_lm))
                    features_dict.update(pd_module.compute_lips_features(lm_list_norm, prev_lm))
                    features_dict.update(pd_module.compute_mouth_features(lm_list_norm, prev_lm))
                    
                    features_dict['Frame'] = frame_idx
                    extracted_data.append(features_dict)
                    
                    # Update global state
                    pd_module._prev_landmarks_global = lm_list_norm
                    
                    # Visualization
                    # 1. Draw Surface Vectors (using raw landmarks for screen position)
                    # We need a previous raw landmarks frame for calculation or just reuse the logic?
                    # pd_module.compute_surface_vectors_split takes whatever we give it. 
                    # If we pass normalized landmarks, the vectors are small. 
                    # vTwo.py passes raw landmarks?
                    # vTwo.py: landmarks = [[lm.x, lm.y, lm.z] for lm in lmks] (raw 0-1 range)
                    # So we should pass landmarks_list (raw) and maintain a previous RAW list.
                    # pd_module._prev_landmarks_global is NORMALIZED. We need a separate raw history for visualization.
                    
                    if not hasattr(self, 'prev_raw_landmarks'):
                        self.prev_raw_landmarks = None
                        
                    self.draw_surface_vectors(vis_frame, landmarks_list, self.prev_raw_landmarks, w, h)
                    self.prev_raw_landmarks = landmarks_list

                    # 2. Draw Landmarks (Green Dots)
                    for idx_set in [
                        pd_module.left_eye_idx, pd_module.right_eye_idx, 
                        pd_module.left_brow_idx, pd_module.right_brow_idx, 
                        pd_module.lip_landmarks_idx,
                        pd_module.left_cheek_idx, pd_module.right_cheek_idx,
                        pd_module.jaw_landmarks_idx,
                        pd_module.mouth_landmarks_idx
                    ]:
                        for idx in idx_set:
                            if idx < len(landmarks):
                                lm = landmarks[idx]
                                cx, cy = int(lm.x * w), int(lm.y * h)
                                cv2.circle(vis_frame, (cx, cy), 1, (0, 255, 0), -1)

                cv2.putText(vis_frame, f"Frame: {frame_idx}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
                cv2.putText(vis_frame, "Extracting Features...", (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)
                
                cv2.imshow('Feature Extraction', vis_frame)
                if cv2.waitKey(1) & 0xFF == 27: # ESC to quit
                    break
        
        cap.release()
        cv2.destroyAllWindows()
        
        if not extracted_data:
            print("No face detected or no data extracted.")
            return

        print("\nFeature Extraction Complete.")
        
        # --- PREPARE DATA FOR INFERENCE ---
        df = pd.DataFrame(extracted_data)
        df = df.fillna(0)
        
        # Ensure all expected columns exist
        missing_cols = [c for c in SELECTED_FEATURES if c not in df.columns]
        if missing_cols:
            print(f"Warning: {len(missing_cols)} expected features are missing. Filling with 0.")
            for c in missing_cols:
                df[c] = 0.0
                
        # Reorder and select
        X_df = df[SELECTED_FEATURES]
        
        # Save CSV
        output_csv = "video_extracted_features.csv"
        X_df.to_csv(output_csv, index=False)
        print(f"Features saved to {output_csv}")
        
        # Prepare Sequence
        X = X_df.values
        seq_len = len(X)
        X_seq = [X[:SEQ_LENGTH] if seq_len > SEQ_LENGTH else X]
        
        # Pad using pd_module logic (padding='post' is default in updated pd.py?)
        # Let's verify pd.py pad_sequences signature or just use it.
        X_padded = pd_module.pad_sequences(X_seq, maxlen=SEQ_LENGTH, dtype='float32')
        
        X_tensor = torch.tensor(X_padded, dtype=torch.float32).to(self.device)
        real_len = min(seq_len, SEQ_LENGTH)
        L_tensor = torch.tensor([real_len], dtype=torch.long).to(self.device)
        
        # Inference
        print("Running Inference...")
        with torch.no_grad():
            outputs = self.model(X_tensor, L_tensor)
            probs = torch.softmax(outputs, dim=1)
            pred_idx = torch.argmax(probs, dim=1).item()
            pred_label = CLASSES[pred_idx]
            confidence = probs[0][pred_idx].item()
            
        print("\n" + "="*40)
        print(f"PREDICTION: {pred_label.upper()}")
        print(f"Confidence: {confidence:.2f}")
        print("="*40 + "\n")


if __name__ == "__main__":
    import argparse
    if len(sys.argv) > 1:
        video_path = sys.argv[1]
    else:
        print("Please provide the video path.")
        video_path = input("Video Path: ").strip()
        video_path = video_path.replace('"', '').replace("'", "")
    
    if not os.path.exists(video_path):
        parent_path = os.path.join("..", video_path)
        if os.path.exists(parent_path):
            print(f"Video found in parent directory: {parent_path}")
            video_path = parent_path
        
    system = ParkinsonDetectionSystem(MODEL_PATH)
    system.process_video_file(video_path)
